import { createSquad } from "./createSquad";
import { TeamData } from "./models";

const teamNames = [
  "Real Madrid",
  "Sevilla",
  "Valencia",
  "Barcelona",
  "Atlético",
  "Mallorca",
  "R. Sociedad",
  "Osasuna",
  "Athletic",
  "Rayo",
  "Villarreal",
  "Cádiz",
  "Levante",
  "Betis",
  "Elche",
  "Espanyol",
  "Granada",
  "Celta",
  "Getafe",
  "Alavés",
] as const;

type TeamName = typeof teamNames[number];

const teams: TeamData[] = [
  {
    name: "Real Madrid",
    quality: "TOP",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Sevilla",
    quality: "GOOD",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Valencia",
    quality: "GOOD",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Barcelona",
    quality: "TOP",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Atlético",
    quality: "TOP",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Mallorca",
    quality: "AVERAGE",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "R. Sociedad",
    quality: "GOOD",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Osasuna",
    quality: "AVERAGE",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Athletic",
    quality: "GOOD",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Rayo",
    quality: "OKAY",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Villarreal",
    quality: "AVERAGE",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Cádiz",
    quality: "POOR",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Levante",
    quality: "POOR",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Betis",
    quality: "POOR",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Elche",
    quality: "MEDIOCRE",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Espanyol",
    quality: "OKAY",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Granada",
    quality: "POOR",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Celta",
    quality: "OKAY",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Getafe",
    quality: "GOOD",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
  {
    name: "Alavés",
    quality: "POOR",
    players: [],
    games: 0,
    points: 0,
    lastResult: "BETWEEN_SEASONS",
    tactic: "4-4-2",
  },
];

function createTeams(): TeamData[] {
  return teams.map((team) => ({ ...team, players: createSquad(team.quality) }));
}

export { createTeams, teams, teamNames };
export type { TeamName };
